### PR TITLE
fix!: avoid parsing in load

### LINKED ISSUE #76: bug: incorrectly parses quoted number/hex string
According to yaml specs, a quoted number/hex string should be parsed as a string, not a number/float.
Currently, this is not respected, and the quoted number/hex string is parsed as a number/float. 

Testcase:

```zig
const std = @import("std");
const yaml = @import("yaml");

test {
    const yml_str =
        \\hex_str: "0xdeadbeef"
    ;

    var value = yaml.Yaml{ .source = yml_str };
    try value.load(std.testing.allocator);
    defer value.deinit(std.testing.allocator);

    try std.testing.expectEqualDeep(
        yaml.Yaml.Value{ .string = "0xdeadbeef" },
        value.docs.items[0].map.get("hex_str").?,
    );
}
```

```
error: 'hex_str_test' failed: expected @typeInfo(Yaml.Value).@"union".tag_type.?.string, found @typeInfo(Yaml.Value).@"union".tag_type.?.int
```

### LINKED ISSUE #81: bug: large integers / floats aren't parseable
`Yaml.Value` hardcodes ints to `i64` and floats to `f64`, so anything larger cannot be parsed properly.

Consider:
```zigconst std = @import("std");
const yaml = @import("yaml");

test {
    const Balances = []u64;
    const yml_str =
        \\[18446744073709551615, 18446744073709551615, 18446744073709551615]
    ;

    var value = yaml.Yaml{ .source = yml_str };
    try value.load(std.testing.allocator);
    try value.parse(std.testing.allocator, Balances);
}
```

I don't know how to improve the situation without a more major architectural change, eg refactoring the union options in `Yaml.Value`.
The spec defines [nodes](https://yaml.org/spec/1.2.2/#nodes) as one of scalar, sequence, or mapping. And I'd expect `load` to only parse the yaml into nodes, and have `Value` map somewhat onto the available node types, but it currently goes somewhat further, eg with int/float/bool parsing.

### PR DESCRIPTION
**Pull request by wemeetagain**
- fixes #81 
- fixes #76 
- supercedes #78 

Previously, `Yaml.Value` had enum options for int, float, boolean, and string, among others.
This lead to various issues improperly loading values (see above).
Its only during the `parse` step that we can properly gather user-provided typing for ints/floats/etc.

To fix this issue, `Yaml.Value` enum options for int, float, boolean, and string, are now all combined into a single option, scalar, some opaque datum.
Parsing this scalar is now defered to the `parse` step, where the user-provided type is used to select the proper codepath.

### CODE REVIEW

File: test/test.zig [hunk 1]
```diff
@@ -89,8 +89,8 @@ const LibTbd = struct {
     },
     install_name: []const u8,
     current_version: union(enum) {
-        string: []const u8,
         int: usize,
+        string: []const u8,
```
Comment (kubkon) [inline test/test.zig:93]: I don't think that change was needed - probably a runaway?

**Review by kubkon — APPROVED** [review]
Looks great, thanks!
